name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: gregson971
  DOCKER_IMAGE_NAME: oc-da-python-p13

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Pythoon
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Initialize venv / Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

      - name: Lint code
        run: |
          . venv/bin/activate
          flake8 --max-line-length=99 --exclude='**/migrations/*,venv'

      - name: Run tests
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        run: |
          . venv/bin/activate
          pytest --cov --cov-config=.coveragerc --cov-fail-under=80

  containerize:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set timestamp for tagging
        id: vars
        run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

      - name: Build and tag Docker image
        run: |
          docker build -t $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:${{ env.TIMESTAMP }} .
          docker tag $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:${{ env.TIMESTAMP }} $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:latest

      - name: Push Docker image
        run: |
          docker push $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:${{ env.TIMESTAMP }}
          docker push $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:latest
